###배터리 상태정보 toss 스토리지 배터리 status2임 
post http://localhost:4000/cars/batteryStatus
Content-Type: application/json; charset=UTF-8

{	
  "device_number" : "888777",
  "charging_percent": "52",
  "battery_power": "64",
  "charging":"1",
  "latitude":"10",
  "longitude": "126.7"
}

###배터리 상태정보 app으로 
POST http://localhost:4000/cars/batteryStatus/app
Content-Type: application/json; charset=UTF-8

{
  "device_number": "888777"
}